In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import accuracy_score,confusion_matrix
from sklearn.datasets import load_iris


In [ ]:
iris=load_iris()
x=iris.data
y=iris.target
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)
regressor=LinearRegression()
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)
print(y_pred)
print(y_test)
accuracy=regressor.score(x_test,y_test)
print(accuracy)


[ 2.06844113  0.96345869 -0.14707913  1.81304847 -0.03927091  2.26261445
 -0.02790835  1.31919261  1.28225236  1.11236814  1.54774304  1.3013147
  1.21150471  1.32946956  1.32977882 -0.12060477  1.35574095  1.21453128
  0.03610115 -0.02518356  1.79941543  1.39427904  0.07356109  0.02146025
  1.59050985 -0.11917603  0.14803648  1.16645127  0.90550234  0.10586947]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
0.9055032992676105


In [ ]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense
from tensorflow.keras.utils import to_categorical

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# Preprocess the target labels
encoder = OneHotEncoder(sparse_output=False)
y = encoder.fit_transform(y.reshape(-1, 1))

# Scale the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Reshape the data to be 3D (samples, timesteps, features) for RNN input
X = X.reshape((X.shape[0], 1, X.shape[1]))

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Build the RNN model
model = Sequential()
model.add(SimpleRNN(50, activation='relu', input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(3, activation='softmax'))

# Compile the model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=50, batch_size=16, validation_data=(X_test, y_test))

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f'Accuracy: {accuracy:.2f}')


Epoch 1/50
8/8 [==============================] - 2s 66ms/step - loss: 1.0364 - accuracy: 0.5417 - val_loss: 1.0020 - val_accuracy: 0.5000
Epoch 2/50
8/8 [==============================] - 0s 11ms/step - loss: 0.9437 - accuracy: 0.5833 - val_loss: 0.9068 - val_accuracy: 0.6333
Epoch 3/50
8/8 [==============================] - 0s 11ms/step - loss: 0.8655 - accuracy: 0.7167 - val_loss: 0.8227 - val_accuracy: 0.7667
Epoch 4/50
8/8 [==============================] - 0s 8ms/step - loss: 0.7967 - accuracy: 0.7333 - val_loss: 0.7522 - val_accuracy: 0.8333
Epoch 5/50
8/8 [==============================] - 0s 11ms/step - loss: 0.7408 - accuracy: 0.7583 - val_loss: 0.6915 - val_accuracy: 0.8333
Epoch 6/50
8/8 [==============================] - 0s 10ms/step - loss: 0.6927 - accuracy: 0.7750 - val_loss: 0.6415 - val_accuracy: 0.8333
Epoch 7/50
8/8 [==============================] - 0s 11ms/step - loss: 0.6527 - accuracy: 0.7833 - val_loss: 0.5994 - val_accuracy: 0.8667
Epoch 8/50
8/8 [============

In [ ]:
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN

x = tf.random.normal((1, 3, 2))

layer = SimpleRNN(4, input_shape=(3, 2))
output = layer(x)

print(output.shape)
# (1, 4)


(1, 4)


In [ ]:
#one hot encoding using OneHotEncoder of Scikit-Learn

import pandas as pd
from sklearn.preprocessing import OneHotEncoder

#Building a dummy employee dataset for example
data = {'Employee id': [10, 20, 15, 25, 30],
        'Gender': ['M', 'F', 'F', 'M', 'F'],
        'Remarks': ['Good', 'Nice', 'Good', 'Great', 'Nice'],
        }
#Converting into a Pandas dataframe
df = pd.DataFrame(data)
#Print the dataframe:
print(f"Employee data : \n{df}")


#Initialize OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)

# Apply one-hot encoding to the categorical columns
one_hot_encoded = encoder.fit_transform(df)
one_hot_df = pd.DataFrame(one_hot_encoded, columns=encoder.get_feature_names_out(categorical_columns))
print(one_hot_encoded)


Employee data : 
   Employee id Gender Remarks
0           10      M    Good
1           20      F    Nice
2           15      F    Good
3           25      M   Great
4           30      F    Nice
[[1. 0. 0. 0. 0. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 1.]]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

# New Section

In [9]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape[0], y_train.shape[0])


60000 60000
