In [1]:
import torch
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

KeyboardInterrupt: 

In [5]:
zero_to_ten = torch.arange(0,20,2)
zero_to_ten

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

NameError: name '_C' is not defined

In [5]:
import torch
tensor = torch.ones(2,2)

for i in range(len(tensor)):
  print(tensor[i] * tensor[i])


tensor([1., 1.])
tensor([1., 1.])


In [4]:
import torch
tensor = torch.ones(2,2)

print(tensor@tensor)


tensor([[2., 2.],
        [2., 2.]])


In [1]:
import torch
t=torch.rand(7,7)
print(t)
print(t.shape)

tensor([[0.0529, 0.3573, 0.8260, 0.3381, 0.0366, 0.5075, 0.9691],
        [0.9240, 0.9366, 0.1250, 0.8088, 0.4658, 0.3084, 0.8953],
        [0.0065, 0.4873, 0.6042, 0.0318, 0.0478, 0.0744, 0.8884],
        [0.1894, 0.7164, 0.5069, 0.7947, 0.2228, 0.1131, 0.9989],
        [0.5165, 0.4598, 0.5292, 0.6008, 0.0310, 0.2914, 0.1455],
        [0.2864, 0.7921, 0.9536, 0.4195, 0.5790, 0.8406, 0.7673],
        [0.5610, 0.5477, 0.5596, 0.7690, 0.7796, 0.7870, 0.5817]])
torch.Size([7, 7])


In [7]:
import torch
t=torch.tensor([1,2,3])
m=torch.matmul(t,t)
print(m)



tensor(14)


In [12]:
import torch
torch.manual_seed(42)
random_tensor_A = torch.rand(3, 4)

torch.manual_seed(42)
random_tensor_B = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)




tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])


In [13]:
import torch
a=torch.rand(size=(3,2))
print(a)


tensor([[0.8694, 0.5677],
        [0.7411, 0.4294],
        [0.8854, 0.5739]])


In [17]:
if torch.cuda.is_available():
  print("hi")

In [1]:
import torch
if torch.cuda.is_available():
  print("hlo")
else:
  print("bye")

hlo


In [4]:
import torch
a=torch.rand(size=(3,2))
print(a.min() ,a.max())
print(a.argmax(),a.argmin())

tensor(0.0113) tensor(0.8769)
tensor(4) tensor(2)
